#!/bin/sh /etc/rc.common
#
# This is free software, licensed under the GNU General Public License v3.
# See /LICENSE for more information.
#

START=90

USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command /usr/bin/speedtest-backend -c /etc/speedtest-go/settings.toml
    procd_set_param stdout 1
    procd_set_param stderr 1
	procd_set_param respawn
    procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger "speedtest-go"
}